FROM roefja/nginx-php:php-7

USER root

# Add Wordpress modules
RUN apk --no-cache add php7-exif php7-fileinfo php7-imagick php7-zip php7-iconv php7-soap

# Copy files from wordpress-builder
COPY --from=wordpress-builder /temp /temp
COPY --from=wordpress-builder /etc/nginx/conf.d/ /etc/nginx/conf.d/
COPY --from=wordpress-builder /usr/src/wordpress/ /usr/src/wordpress/
COPY  ./config/supervisord.php-7.conf /etc/supervisor/conf.d/supervisord.conf

USER nginx